version: '3.0'
services:
  mqttwrapper:
    build: .
    ports:
    - 5680:4000
    environment:
    - MQTT_BROKER=1.2.3.4
    - MQTT_PORT=1883
    - MQTT_USERNAME=abc
    - MQTT_PASSWORD=abc
    - REDIS_HOST=1.2.3.4
    - REDIS_PORT=6379
    #logging:
    #  driver: syslog
    #  options:
    #    tag: "{{.Name}}/{{.ID}}"
    networks:
    - backend

networks:
  backend:
